config/routes.rb
  Rails.application.routes.draw do

  devise_for :users, path: "/", path_names: { sign_in: 'signin', sign_out: 'signout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: '', sign_up: 'signup' }, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}

    root to: 'site#index'

    get '/about', to: 'site#about'

    get '/destinations', to: 'destinations#index'

    get '/blog', to: 'site#blog'

    get '/faq', to: 'site#faq'

    get '/contact', to: 'site#contact'

    get '/signup', to: 'site#signup'

    post '/hotels', to: 'site#hotels'

    post '/', to: 'site#hotels'

    get '/hotels/:hotelId', to: 'site#hotel'

    get '/bucketlist', to: 'bucketlist_items#index'

    get '/hotels', to: 'site#responsible_search'

  resources :bucketlist_items, only: [:create, :destroy, :index]

 resources :destinations

end

app/models/destination.rb
class Destination < ActiveRecord::Base
  belongs_to :user
  has_many :bucketlist_items
  accepts_nested_attributes_for :bucketlist_items


  has_attached_file :image, styles: { large: "670x520", medium: "300x220>", thumb: "150x150#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

	def index
    @destinations = Destination.all
	end

	def show
		@destination = Destination.find(params[:id])
	end

	def edit
		@destination = Destination.find(params[:id])
	end

  def new
    @destination = Destination.new
  end

  def create
    @destination = Destination.new(destination_params)
   

     respond_to do |format|
    if @destination.save
      format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
      format.json { render :show, status: :created, location: @destination }
    else
      format.html { render :new }
      format.json { render json: @destination.errors, status: :unprocessable_entity }
    end
  end
  end

	def update
    destination_id = params[:id]
    destination = Destination.find(destination_id)

    destination.update_attributes(destination_params)

    redirect_to "/destinations"
  end

private
  def destination_params
      params.require(:destination).permit(:name, :location, :website, :certification, :category, :desc_prod, :desc_good, :directions, :recommended, :seo_tags, :image_url )
    end
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
        <% @destination.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :certification %><br>
    <%= f.text_field :certification %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :desc_prod %><br>
    <%= f.text_field :desc_prod %>
  </div>
  <div class="field">
    <%= f.label :desc_good %><br>
    <%= f.text_field :desc_good %>
  </div>
    <div class="field">
    <%= f.label :directions %><br>
    <%= f.text_field :directions %>
  </div>
  <div class="field">
    <%= f.label :recommended %><br>
    <%= f.text_field :recommended %>
  </div>
  <div class="field">
    <%= f.label :seo_tags %><br>
    <%= f.text_field :seo_tags %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>

  </div>


<br></br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @destinations %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/edit.html.erb
<h1>PRIVATE CONSOLE PAGE TO AMEND DESTINATIONS</h1>

<%= render 'form' %>

app/views/destinations/index.html.erb
<%= render './site/head' %>
<%= render './site/nav' %>

<div class="container">
  <h1 class="page-title">Destinations</h1>
</div>

<div class="container">
  <div id="popup-gallery">
    <div class="row row-col-gap">
      <div class="col-md-4">
        <ul>
          <!-- Loop through destinations -->
          <% @destinations.each do |d| %>
            <li>
              <a class="hover-img popup-gallery-image" href="/destinations/<%= d.id %>">
                <img src="<%= d.image_url %>" alt="Sri Lanka Rice Paddies" title="Responsible Bike Tour Sri Lanka" />
              </a>
              <!-- Show destination info -->
              <%= d.name %><br>
              <%= d.location %><br>
              <%= d.category %><br>
              <!-- Setup form for creating new bucketlist items -->
              <% if current_user %>
              <% if current_user.has_bucket_list_item?(d.id) %>
                <%= link_to "Remove from Bucket List", { :controller => "bucketlist_items",
                                :action => "destroy",
                                :id => d.id },
                                :method => :delete %>
              <% else %>
                <div>
                  <div style="display:none;">
                    <%= form_for BucketlistItem.new do |f| %>
                      <!-- Enter destination id -->
                      <%= f.hidden_field :destination_id, value: d.id %>
                      <%= f.submit "Add to Bucket List" %>
                    <% end %>
                  </div>
                  <i class="fa fa-heart round box-icon-small hover-icon i round">
                  </i>
                </div>
              <% end %>
              <% end %>
              <br>
              <br>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>



<div class="gap"></div>

<%= render './site/footer' %>

app/views/destinations/new.html.erb
<div>
  <h1>PRIVATE PAGE TO MAKE NEW DESTINATIONS</h1>
  <%= render 'form' %>
</div>

app/views/destinations/show.html.erb
<%= render './site/head' %>
<%= render './site/nav' %>


<div class="container">
  <div itemscope itemtype="http://schema.org/Restaurant">
    <h2 class="page-title" span itemprop="name" style="display: inline;"> <%= @destination.name%> </span>
    </h2>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <aside class="sidebar-left">
          <div class="sidebar-widget">
            <div class="Form">
              <input class="form-control" placeholder="Search..." type="text" />
              
            </div>
          </div>
       <!--    <div class="sidebar-widget">
            <h4>Categories</h4>
            <ul class="icon-list list-category">
              <li>
                <a href="#"><i class="fa fa-angle-right"></i>Photos <small >(63)</small></a>
              </li>
              <li>
                <a href="#"><i class="fa fa-angle-right"></i>Vacation <small >(94)</small></a>
              </li>
              <li>
                <a href="#"><i class="fa fa-angle-right"></i>Flights <small >(56)</small></a>
              </li>
              <li>
                <a href="#"><i class="fa fa-angle-right"></i>Travel Advices <small >(80)</small></a>
              </li>
              <li>
                <a href="#"><i class="fa fa-angle-right"></i>Trending Now <small >(83)</small></a>
              </li>
              <li>
                <a href="#"><i class="fa fa-angle-right"></i>Hotels <small >(89)</small></a>
              </li>
              <li>
                <a href="#"><i class="fa fa-angle-right"></i>Places to Go <small >(69)</small></a>
              </li>
              <li>
                <a href="#"><i class="fa fa-angle-right"></i>Travel Stories <small >(64)</small></a>
              </li>
            </ul>
          </div>
          <div class="sidebar-widget">
              <h4>Twitter Feed</h4>
              <div class="twitter" id="twitter"></div>
          </div>
          <div class="sidebar-widget">
            <h4>Recent Comments</h4>
              <ul class="thumb-list thumb-list-right">
                <li>
                  <a href="#">
                    <img class="rounded" src="img/70x70.png" alt="Image Alternative text" title="Afro" />
                  </a>
                  <div class="thumb-list-item-caption">
                    <p class="thumb-list-item-meta">6 minutes ago</p>
                    <h4 class="thumb-list-item-title"><a href="#">Keith Churchill</a></h4>
                    <p class="thumb-list-item-desciption">Erat praesent cursus taciti a dictum ridiculus...</p>
                  </div>
                </li>
                <li>
                  <a href="#">
                    <img class="rounded" src="img/70x70.png" alt="Image Alternative text" title="Gamer Chick" />
                  </a>
                  <div class="thumb-list-item-caption">
                    <p class="thumb-list-item-meta">5 minutes ago</p>
                    <h4 class="thumb-list-item-title"><a href="#">Joseph Hudson</a></h4>
                    <p class="thumb-list-item-desciption">Iaculis faucibus etiam nisl facilisi massa ut...</p>
                  </div>
                </li>
                <li>
                  <a href="#">
                    <img class="rounded" src="img/70x70.png" alt="Image Alternative text" title="AMaze" />
                  </a>
                  <div class="thumb-list-item-caption">
                    <p class="thumb-list-item-meta">5 minutes ago</p>
                    <h4 class="thumb-list-item-title"><a href="#">Cheryl Gustin</a></h4>
                    <p class="thumb-list-item-desciption">Tempor risus quisque egestas venenatis potenti lobortis...</p>
                  </div>
                </li>
              </ul>
          </div> -->
        </aside>
      </div>

      <div class="col-md-9">
        <!-- START BLOG POST -->
        <div class="article post">
          <header class="post-header">
            <a class="hover-img" href="#">
              <img src="<%= @destination.image_url %>" alt="<%= @destination.name %>" title="<%= @destination.seo_tags %>" /><i class="fa fa-heart round box-icon-small hover-icon i round"></i>
            </a>
          </header>
          <div class="post-inner">
            <ul class="post-meta">
              
              <li>
                <i class="fa fa-map-marker"></i><a href="#"><%= @destination.location %></a>
              </li>
              <li>
                <i class="fa fa-tags"></i><a href="#"><%= @destination.seo_tags %></a>
              </li>
              <li>
                <i class="fa fa-user"></i><a href="#">LOTUS Nomads</a>
              </li>
              <li>
                <i class="fa fa-calendar"></i><a href="#"><%= @destination.created_at %></a>
              </li>
              <li>
                <!-- Setup form for creating new bucketlist items -->
              <% if current_user %>
              <% if current_user.has_bucket_list_item?(@destination.id) %>
                <%= link_to "Remove from Bucket List", { :controller => "bucketlist_items",
                                :action => "destroy",
                                :id => @destination.id },
                                :method => :delete %>
              <% else %>
                <div>
                  <div style="display:none;">
                    <%= form_for BucketlistItem.new do |f| %>
                      <!-- Enter destination id -->
                      <%= f.hidden_field :destination_id, value: @destination.id %>
                      <%= f.submit "Add to Bucket List" %>
                    <% end %>
                  </div>
                  <i class="fa fa-heart round box-icon-small hover-icon i round">
                  </i>
                </div>
              <% end %>
              <% end %>
              </li>
            </ul>

            <h3>The Goods</h3>
            
            <%= @destination.desc_prod %>
            <br>
            <br>
            <h3>The Good</h3>
            <%= @destination.desc_good %>
            <br>
            <br>
            <h3>Don't Miss</h3>
            <%= @destination.recommended%>
            <br>
            <br>
            <h4>Getting There</h4>
            <%= @destination.directions%>
            <br>
            <br>
            <h4>Learn More</h4>
            <a target= "_blank" href="<%= @destination.website%>"><%= @destination.website %></a>
            <br>
            <br>
          </div>
        </div>
        <!-- END BLOG POST -->

        <div class="gap"></div>
      </div>
    </div>
  </div>
</div>

<%= render './site/footer' %>